im lazy fr

diff --git a/testing b/testing
--- a/testing
+++ b/testing
@@ -3,8 +3,6 @@
 valgrind=""
 output="~/.output_exe"
 
-pwd
-
 while getopts "v" opt; do
   case $opt in
     v)
@@ -17,4 +15,25 @@ while getopts "v" opt; do
   esac
 done
 
+#simple testing
+for file in test*.in; do
+  test_number="${test_file%.*}"
+  ./"${source_file%.*}" < "$test_file" > "$test_number.out"
+  if diff -q "$test_number.out" "$test_number.expected" >/dev/null; then
+      echo -e "${GREEN}Test $test_number passed.${NC}"
+  else
+      echo -e "${RED}Test $test_number failed.${NC}"
+  fi
+done
+
+if [ "$valgrind" ]; then
+  for test_file in test*.in; do
+    test_number="${test_file%.*}"
+    if ! valgrind_output=$(valgrind --leak-check=full ./"${source_file%.*}" < "$test_file" 2>&1 | grep "definitely lost"); then
+        echo -e "${GREEN}No memory leaks found in test $test_number.${NC}"
+    else
+        echo -e "${RED}Memory leaks found in test $test_number.${NC}"
+    fi
+  done
+fi
 
